/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsRouteImport } from './routes/us'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivateRouteImport } from './routes/private'
import { Route as DeenRouteImport } from './routes/deen'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsStudyingRouteImport } from './routes/us.studying'
import { Route as UsHabitsRouteImport } from './routes/us.habits'
import { Route as UsGalleryRouteImport } from './routes/us.gallery'

const UsRoute = UsRouteImport.update({
  id: '/us',
  path: '/us',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => rootRouteImport,
} as any)
const DeenRoute = DeenRouteImport.update({
  id: '/deen',
  path: '/deen',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsStudyingRoute = UsStudyingRouteImport.update({
  id: '/studying',
  path: '/studying',
  getParentRoute: () => UsRoute,
} as any)
const UsHabitsRoute = UsHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => UsRoute,
} as any)
const UsGalleryRoute = UsGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => UsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/deen': typeof DeenRoute
  '/private': typeof PrivateRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/setup': typeof SetupRoute
  '/today': typeof TodayRoute
  '/unlock': typeof UnlockRoute
  '/us': typeof UsRouteWithChildren
  '/us/gallery': typeof UsGalleryRoute
  '/us/habits': typeof UsHabitsRoute
  '/us/studying': typeof UsStudyingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/deen': typeof DeenRoute
  '/private': typeof PrivateRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/setup': typeof SetupRoute
  '/today': typeof TodayRoute
  '/unlock': typeof UnlockRoute
  '/us': typeof UsRouteWithChildren
  '/us/gallery': typeof UsGalleryRoute
  '/us/habits': typeof UsHabitsRoute
  '/us/studying': typeof UsStudyingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/deen': typeof DeenRoute
  '/private': typeof PrivateRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/setup': typeof SetupRoute
  '/today': typeof TodayRoute
  '/unlock': typeof UnlockRoute
  '/us': typeof UsRouteWithChildren
  '/us/gallery': typeof UsGalleryRoute
  '/us/habits': typeof UsHabitsRoute
  '/us/studying': typeof UsStudyingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/counter'
    | '/deen'
    | '/private'
    | '/reset-password'
    | '/set-password'
    | '/setup'
    | '/today'
    | '/unlock'
    | '/us'
    | '/us/gallery'
    | '/us/habits'
    | '/us/studying'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/counter'
    | '/deen'
    | '/private'
    | '/reset-password'
    | '/set-password'
    | '/setup'
    | '/today'
    | '/unlock'
    | '/us'
    | '/us/gallery'
    | '/us/habits'
    | '/us/studying'
  id:
    | '__root__'
    | '/'
    | '/counter'
    | '/deen'
    | '/private'
    | '/reset-password'
    | '/set-password'
    | '/setup'
    | '/today'
    | '/unlock'
    | '/us'
    | '/us/gallery'
    | '/us/habits'
    | '/us/studying'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CounterRoute: typeof CounterRoute
  DeenRoute: typeof DeenRoute
  PrivateRoute: typeof PrivateRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SetupRoute: typeof SetupRoute
  TodayRoute: typeof TodayRoute
  UnlockRoute: typeof UnlockRoute
  UsRoute: typeof UsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/us': {
      id: '/us'
      path: '/us'
      fullPath: '/us'
      preLoaderRoute: typeof UsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private': {
      id: '/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deen': {
      id: '/deen'
      path: '/deen'
      fullPath: '/deen'
      preLoaderRoute: typeof DeenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us/studying': {
      id: '/us/studying'
      path: '/studying'
      fullPath: '/us/studying'
      preLoaderRoute: typeof UsStudyingRouteImport
      parentRoute: typeof UsRoute
    }
    '/us/habits': {
      id: '/us/habits'
      path: '/habits'
      fullPath: '/us/habits'
      preLoaderRoute: typeof UsHabitsRouteImport
      parentRoute: typeof UsRoute
    }
    '/us/gallery': {
      id: '/us/gallery'
      path: '/gallery'
      fullPath: '/us/gallery'
      preLoaderRoute: typeof UsGalleryRouteImport
      parentRoute: typeof UsRoute
    }
  }
}

interface UsRouteChildren {
  UsGalleryRoute: typeof UsGalleryRoute
  UsHabitsRoute: typeof UsHabitsRoute
  UsStudyingRoute: typeof UsStudyingRoute
}

const UsRouteChildren: UsRouteChildren = {
  UsGalleryRoute: UsGalleryRoute,
  UsHabitsRoute: UsHabitsRoute,
  UsStudyingRoute: UsStudyingRoute,
}

const UsRouteWithChildren = UsRoute._addFileChildren(UsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CounterRoute: CounterRoute,
  DeenRoute: DeenRoute,
  PrivateRoute: PrivateRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
  SetupRoute: SetupRoute,
  TodayRoute: TodayRoute,
  UnlockRoute: UnlockRoute,
  UsRoute: UsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
